import Head from "next/head";
import Link from "next/link";
import { useContext } from "react";

import AuthContext from "~/contexts/AuthContext";
import Button from "~/components/Button";
import BackButton from "~/components/BackButton";
import SearchBar from "~/components/SearchBar";
import Navbar from "~/components/layout/Navbar";
import Comment from "../components/C1-1components/comment/Comment";
import UserCard from "~/components/E1-1/UserCard";

export default function Index() {
  const user = useContext(AuthContext);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="m-4 flex items-center gap-3">
        <Button type="border">キャンセル</Button>
        <Button type="fill">保存</Button>
        <SearchBar></SearchBar>
        <BackButton />
      </div>

      <div className="m-6 grid grid-cols-4 gap-5">
        <UserCard name="吉田憲一郎" company="Money Forward" />
        <UserCard name="辻庸介" company="Suntory" university="ハノイ国家大学" />
        <UserCard name="吉田憲一郎" company="Money Forward" />
        <UserCard name="辻庸介" university="ハノイ国家大学" />
        <UserCard name="鳥井信吾" />
      </div>
    </div>
  );
}
