{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.names.fullname" . -}}
apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if and .Values.ingress.ingressClassName (eq "false" (include "common.ingress.supportsIngressClassname" .)) }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (include "common.ingress.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      - path: "/"
        {{ template "common.ingress.pathType" (dict "context" $ "value" .pathType) }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-web" $fullName) "servicePort" "http" "context" $) | nindent 10 }}
      - path: "/(api|telescope|broadcasting|vendor)"
        {{ template "common.ingress.pathType" (dict "context" $ "value" .pathType) }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-api" $fullName) "servicePort" "http" "context" $) | nindent 10 }}
  {{- end }}
{{- end }}
