<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ScoreEachSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('score_eaches')->insert([
            [
                'part_name' => '言語知識',
                'expected_score' => 41,
                'result' => 53,
                'test_content_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 42,
                'result' => 51,
                'test_content_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 43,
                'result' => 39,
                'test_content_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 230,
                'result' => 245,
                'test_content_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 434,
                'result' => 234,
                'test_content_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '言語知識',
                'expected_score' => 34,
                'result' => 54,
                'test_content_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 4,
                'result' => 10,
                'test_content_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 19,
                'result' => 23,
                'test_content_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 322,
                'result' => 235,
                'test_content_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 354,
                'result' => 231,
                'test_content_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '言語知識',
                'expected_score' => 42,
                'result' => 23,
                'test_content_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 34,
                'result' => 43,
                'test_content_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 23,
                'result' => 32,
                'test_content_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 445,
                'result' => 332,
                'test_content_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 234,
                'result' => 345,
                'test_content_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '言語知識',
                'expected_score' => 33,
                'result' => 54,
                'test_content_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 12,
                'result' => 34,
                'test_content_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 19,
                'result' => 21,
                'test_content_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 411,
                'result' => 211,
                'test_content_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 423,
                'result' => 231,
                'test_content_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '言語知識',
                'expected_score' => 31,
                'result' => 52,
                'test_content_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 51,
                'result' => 32,
                'test_content_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 34,
                'result' => 55,
                'test_content_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 422,
                'result' => 200,
                'test_content_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 413,
                'result' => 344,
                'test_content_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '言語知識',
                'expected_score' => 41,
                'result' => 52,
                'test_content_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 45,
                'result' => 31,
                'test_content_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 43,
                'result' => 53,
                'test_content_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 444,
                'result' => 222,
                'test_content_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 433,
                'result' => 333,
                'test_content_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '言語知識',
                'expected_score' => 44,
                'result' => 55,
                'test_content_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 11,
                'result' => 22,
                'test_content_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 12,
                'result' => 23,
                'test_content_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 123,
                'result' => 456,
                'test_content_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 234,
                'result' => 345,
                'test_content_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '言語知識',
                'expected_score' => 12,
                'result' => 23,
                'test_content_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 34,
                'result' => 45,
                'test_content_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 56,
                'result' => 23,
                'test_content_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 123,
                'result' => 234,
                'test_content_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 231,
                'result' => 495,
                'test_content_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '言語知識',
                'expected_score' => 60,
                'result' => 10,
                'test_content_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '読解',
                'expected_score' => 60,
                'result' => 12,
                'test_content_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => '聴解',
                'expected_score' => 60,
                'result' => 12,
                'test_content_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Reading',
                'expected_score' => 400,
                'result' => 200,
                'test_content_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'part_name' => 'Listening',
                'expected_score' => 400,
                'result' => 200,
                'test_content_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
