<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'username' => 'kien20215071',
                'email' => 'kien20215071@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Trần Đức Kiên',
                'japanese_fullname' => 'チャン・ドゥック・キエン',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 1,
                'grade_code' => 'K64',
                'receive_naitei_date' => '2020-01-01',
                'graduation_date' => '2020-01-01',
            ],
            [
                'username' => 'nam20210615',
                'email' => 'nam20210615@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Đỗ Nguyễn Hải Nam',
                'japanese_fullname' => 'ド・グエン・ハイ・ナム',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 1,
                'grade_code' => 'K66',
                'receive_naitei_date' => '2020-01-01',
                'graduation_date' => '2020-01-01',
            ],
            [
                'username' => 'minh20215090',
                'email' => 'minh20215090@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mai Nhật Minh',
                'japanese_fullname' => 'マイ・ニャット・ミン',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 1,
                'grade_code' => 'K66',
                'receive_naitei_date' => '2020-01-01',
                'graduation_date' => '2020-01-01',
            ],
            [
                'username' => 'manh20215087',
                'email' => 'manh20215087@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Nguyễn Phúc Mạnh',
                'japanese_fullname' => 'グエン・フック・マイン',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 1,
                'grade_code' => 'K66',
                'receive_naitei_date' => '2020-01-01',
                'graduation_date' => '2020-01-01',
            ],
            [
                'username' => 'mentor1',
                'email' => 'mentor1@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor1',
                'japanese_fullname' => 'メンター１',
                'avatar' => 'https://i.pinimg.com/736x/d4/1c/e6/d41ce64d50c3e3a49884b05fa41dc3b5.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor2',
                'email' => 'mentor2@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor2',
                'japanese_fullname' => 'メンター2',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor3',
                'email' => 'mentor3@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor3',
                'japanese_fullname' => 'メンター3',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor4',
                'email' => 'mentor4@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor4',
                'japanese_fullname' => 'メンター4',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor5',
                'email' => 'mentor5@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor5',
                'japanese_fullname' => 'メンター5',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor6',
                'email' => 'mentor6@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor6',
                'japanese_fullname' => 'メンター6',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor7',
                'email' => 'mentor7@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor7',
                'japanese_fullname' => 'メンター',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor8',
                'email' => 'mentor8@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor8',
                'japanese_fullname' => 'メンター8',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor9',
                'email' => 'mentor9@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor9',
                'japanese_fullname' => 'メンター9',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor10',
                'email' => 'mentor10@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor10',
                'japanese_fullname' => 'メンター10',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor11',
                'email' => 'mentor11@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor11',
                'japanese_fullname' => 'メンター11',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor12',
                'email' => 'mentor12@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor12',
                'japanese_fullname' => 'メンター12',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor13',
                'email' => 'mentor13@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor13',
                'japanese_fullname' => 'メンター13',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'mentor14',
                'email' => 'mentor14@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Mentor14',
                'japanese_fullname' => 'メンター14',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 2,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'teacher1',
                'email' => 'teacher1@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Teacher1',
                'japanese_fullname' => 'ティーチャー1',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 3,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'teacher2',
                'email' => 'teacher2@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Teacher2',
                'japanese_fullname' => 'ティーチャー2',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 3,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'teacher3',
                'email' => 'teacher3@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Teacher3',
                'japanese_fullname' => 'ティーチャー3',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 3,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'teacher4',
                'email' => 'teacher4@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Teacher4',
                'japanese_fullname' => 'ティーチャー4',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 3,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'manager1',
                'email' => 'manager1@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Manager1',
                'japanese_fullname' => 'マネージャー1',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 4,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'manager2',
                'email' => 'manager2@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Manager2',
                'japanese_fullname' => 'マネージャー2',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 4,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'manager3',
                'email' => 'manager3@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Manager3',
                'japanese_fullname' => 'マネージャー3',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 4,
                'grade_code' => null,
                'receive_naitei_date' => null,
                'graduation_date' => null,
            ],
            [
                'username' => 'son20215132',
                'email' => 'son20215132@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Nguyễn Trung Sơn',
                'japanese_fullname' => 'グエン・チュン・ソン',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 1,
                'grade_code' => 'K66',
                'receive_naitei_date' => '2020-01-01',
                'graduation_date' => '2020-01-01',
            ],
            [
                'username' => 'quang20210725',
                'email' => 'quang20210725@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Tống Chí Quang',
                'japanese_fullname' => 'トン・チー・クアン',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 1,
                'grade_code' => 'K66',
                'receive_naitei_date' => '2020-01-01',
                'graduation_date' => '2020-01-01',
            ],
            [
                'username' => 'truong20194698',
                'email' => 'truong20194698@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Nguyễn Đức Trưởng',
                'japanese_fullname' => 'グエン・ドゥック・チュオン',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2022/03/Avatar-Gau.jpg',
                'role' => 1,
                'grade_code' => 'K64',
                'receive_naitei_date' => '2020-01-01',
                'graduation_date' => '2020-01-01',
            ],
            [
                'username' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => bcrypt('123456'),
                'vietnamese_fullname' => 'Admin',
                'japanese_fullname' => 'アドミン',
                'avatar' => 'https://res.cloudinary.com/kien-save-img/image/upload/v1661825717/three-persons-admin-icon-outline-600w-1730974165_e5a306.webp',
                'role' => 0,
                'grade_code' => null,
                'receive_naitei_date' => '2020-01-01',
                'graduation_date' => '2020-01-01',
            ],
        ]);
    }
}
