apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.api.config.app.name | quote }}
  APP_ENV: {{ .Values.api.config.app.env | quote }}
  APP_DEBUG: {{ .Values.api.config.app.debug | quote }}
  APP_URL: {{ .Values.api.config.app.url | quote }}
  LOG_CHANNEL: {{ .Values.api.config.log.channel | quote }}
  LOG_LEVEL: {{ .Values.api.config.log.level | quote }}
  DB_HOST: {{ include "splan.db.host" . | quote }}
  DB_PORT: {{ include "splan.db.port" . | quote }}
  DB_DATABASE: {{ include "splan.db.database" . | quote }}
  DB_USERNAME: {{ include "splan.db.username" . | quote }}
  FILESYSTEM_DRIVER: {{ .Values.api.config.filesystems.default | quote }}
  FILESYSTEM_CLOUD: {{ .Values.api.config.filesystems.cloud | quote }}
  AWS_DEFAULT_REGION: {{ .Values.api.config.filesystems.s3.region | quote }}
  AWS_BUCKET: {{ .Values.api.config.filesystems.s3.bucket | quote }}
  AWS_ENDPOINT: {{ .Values.api.config.filesystems.s3.endpoint | quote }}
  AWS_S3_FORCE_PATH_STYLE: {{ .Values.api.config.filesystems.s3.forcePathStyle | quote }}
  BROADCAST_DRIVER: {{ .Values.api.config.broadcast.driver | quote }}
  CACHE_DRIVER: {{ .Values.api.config.cache.driver | quote }}
  QUEUE_CONNECTION: {{ .Values.api.config.queue.connection | quote }}
  SESSION_DRIVER: {{ .Values.api.config.session.driver | quote }}
  REDIS_HOST: {{ include "splan.redis.host" . | quote }}
  REDIS_PORT: {{ include "splan.redis.port" . | quote }}
  BEANSTALKD_HOST: {{ include "splan.beanstalkd.host" . | quote }}
  MAIL_DRIVER: {{ .Values.api.config.mail.mailer | quote }}
  MAIL_HOST: {{ .Values.api.config.mail.smtp.host | quote }}
  MAIL_PORT: {{ .Values.api.config.mail.smtp.port | quote }}
  MAIL_ENCRYPTION: {{ .Values.api.config.mail.smtp.encryption | quote }}
  MAIL_FROM_ADDRESS: {{ .Values.api.config.mail.from.address | quote }}
  MAIL_FROM_NAME: {{ .Values.api.config.mail.from.name | quote }}
  SENTRY_LARAVEL_DSN: {{ .Values.api.config.sentry.dsn | quote }}
  SENTRY_TRACES_SAMPLE_RATE: {{ .Values.api.config.sentry.tracesSampleRate | quote }}
  {{- range $name, $value := .Values.api.extraEnvVars }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
