apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ .Values.api.config.app.key | required "Application encryption key is required" | b64enc | quote }}
  DB_PASSWORD: {{ include "splan.db.password" . | b64enc | quote }}
  REDIS_PASSWORD: {{ include "splan.redis.password" . | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.api.config.filesystems.s3.accessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.api.config.filesystems.s3.secretKey | b64enc | quote }}
