apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-web
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  {{- if eq .Values.web.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.web.service.externalTrafficPolicy }}
  {{- if .Values.web.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.web.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.web.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.web.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if and (eq .Values.web.service.type "ClusterIP") .Values.web.service.clusterIP }}
  clusterIP: {{ .Values.web.service.clusterIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.web.service.port }}
    targetPort: http
    {{- if (and (has .Values.web.service.type (list "NodePort" "LoadBalancer")) (not (empty .Values.web.service.nodePort))) }}
    nodePort: {{ .Values.web.service.nodePort }}
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
